[package]
name = "guess"
version = "0.1.0"
authors = ["Paul Stey <paulstey@gmail>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
